# Generated by Django 4.2 on 2023-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConatctModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(blank=True, help_text='021-----', null=True, verbose_name='شماره تلفن شخصی')),
                ('phone', models.BigIntegerField(blank=True, help_text='0912----', null=True, verbose_name='شماره تلفن مغازه')),
                ('email', models.EmailField(blank=True, help_text='mobin@gmail.com', max_length=254, null=True, verbose_name='ایمیل')),
                ('instagram_id', models.CharField(blank=True, help_text='id', max_length=30, null=True, verbose_name='آیدی اینستا گرام')),
                ('instagram_link', models.URLField(blank=True, help_text='link', null=True, verbose_name='لینک اینستا گرام')),
                ('youtube_chanel', models.CharField(blank=True, help_text='chanel name', max_length=30, null=True, verbose_name='کانال اینستا یوتوب')),
                ('youtube_chanel_link', models.URLField(blank=True, help_text='link', null=True, verbose_name='لینک یوتوب')),
            ],
        ),
    ]
