# Generated by Django 4.2 on 2023-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_conatctmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='اسم کاربر')),
                ('content', models.CharField(blank=True, max_length=40, null=True, verbose_name='موضوع')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن کاربر')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='سوال یا نظرر کابر')),
            ],
            options={
                'verbose_name_plural': 'تماس کاربر',
            },
        ),
        migrations.AlterModelOptions(
            name='conatctmodel',
            options={'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.RemoveField(
            model_name='conatctmodel',
            name='phone_number',
        ),
    ]
