# Generated by Django 4.2 on 2023-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_usercontactmodel_alter_conatctmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conatctmodel',
            name='youtube_chanel',
        ),
        migrations.RemoveField(
            model_name='conatctmodel',
            name='youtube_chanel_link',
        ),
        migrations.AddField(
            model_name='conatctmodel',
            name='addres',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='آدرس'),
        ),
    ]
