# Generated by Django 4.2 on 2023-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام')),
                ('working_expariance', models.ImageField(blank=True, null=True, upload_to='', verbose_name='سابقه ی کاری')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_photo', verbose_name='عکس')),
            ],
        ),
    ]
