# Generated by Django 4.2 on 2023-06-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name_plural': 'درباره ما'},
        ),
    ]
