# Generated by Django 4.2 on 2023-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_aboutusmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='working_expariance',
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='تجربه ی کاری'),
        ),
    ]
