# Generated by Django 4.2 on 2023-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, help_text='مثال : بوگاتی', max_length=30, null=True, verbose_name='اسم ماشین')),
                ('quantity', models.CharField(blank=True, max_length=40, null=True, verbose_name='کیفیت روغن')),
                ('liter', models.IntegerField(blank=True, null=True, verbose_name='لیتر روغن')),
                ('sug_oils', models.CharField(blank=True, max_length=40, null=True, verbose_name='روغن های بیشنهادی ما')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='cars_images', verbose_name='عکس ماشین')),
            ],
            options={
                'verbose_name_plural': 'ماشین ها ',
            },
        ),
    ]
