# Generated by Django 4.2 on 2023-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='اسم ماشین')),
                ('brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='برند ماشین')),
                ('qaulity_ois', models.CharField(blank=True, max_length=40, null=True, verbose_name='کیفیت روغن')),
                ('liter_oils', models.IntegerField(blank=True, null=True, verbose_name='لیتر روغن')),
                ('sug_oils', models.CharField(blank=True, max_length=40, null=True, verbose_name='روغن های بیشنهادی ما')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>---عکس سوم', verbose_name='عکس سوم')),
            ],
            options={
                'verbose_name_plural': 'ماشین ها ',
            },
        ),
        migrations.DeleteModel(
            name='CarsModel',
        ),
    ]
