# Generated by Django 4.2 on 2023-06-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_second_image_cars_third_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='ماشین', verbose_name='عکس ماشین'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='ماشین', verbose_name='عکس دوم'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='ماشین', verbose_name='عکس سوم'),
        ),
    ]
