# Generated by Django 4.2 on 2023-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_main_image_alter_cars_second_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='third_image',
        ),
    ]
