# Generated by Django 4.2 on 2023-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cars_second_image_cars_third_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='third_image',
        ),
    ]
