# Generated by Django 4.2 on 2023-06-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_cars_second_image_remove_cars_third_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='main_image',
            new_name='img_one',
        ),
    ]
