# Generated by Django 4.2 on 2023-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carsmodel_delete_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='img_one',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars1', verbose_name='عکس ماشین'),
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='second_img',
            field=models.ImageField(blank=True, null=True, upload_to='cars2', verbose_name='عکس دوم'),
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='third_img',
            field=models.ImageField(blank=True, null=True, upload_to='cars3', verbose_name='عکس سوم'),
        ),
    ]
